language: python

python:
  - 3.4
  - 3.3
  - 2.7

install:
  - pip install -r requirements-test.txt codecov

script:
  - python setup.py test
  - python setup.py sdist
  - pip install ./dist/*.tar.gz

after_success: codecov
