# Configure.
language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
sudo: false

# Environment and matrix.
env: TOX_ENV=py
matrix:
  include:
    - python: 3.5
      env: TOX_ENV=lint
      after_success: []
    - python: 3.5
      env: TOX_ENV=docs
      after_success:
        - eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 docs/key
        - openssl aes-256-cbc -d -K "$encrypted_xxxxxxxxxxxx_key" -iv "$encrypted_xxxxxxxxxxxx_iv"
          < docs/key.enc > docs/key && ssh-add docs/key
        - git config --global user.email "builds@travis-ci.com"
        - git config --global user.name "Travis CI"
        - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
        - export ${!TRAVIS*}
        - tox -e docsV

# Run.
install: pip install tox
script: tox -e $TOX_ENV
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Deploy.
deploy:
  provider: pypi
  user: Robpol86
  password:
    secure:
      "multi\
      line\
      encrypted"
  on:
    condition: $TRAVIS_PYTHON_VERSION = 3.4
    tags: true
